### ISSUE TITLE
Unit_hipStreamCreateWithPriority_ValidateWithEvents 

### ISSUE THREAD

**Issue by pvelesko** [CHIP-SPV/chipStar#251]
One of the flaky tests that was excluded for 0.9

**Comment by pvelesko** [comment]
```
Thread 3 "hipStreamCreate" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffe2936700 (LWP 10533)]
0x00007ffff658bc3d in __memmove_avx_unaligned_erms_rtm () from /lib64/libc.so.6
(gdb)
(gdb) bt
#0  0x00007ffff658bc3d in __memmove_avx_unaligned_erms_rtm () from /lib64/libc.so.6
#1  0x00007ffff7a31ce7 in std::__copy_move<true, true, std::random_access_iterator_tag>::__copy_m<CHIPEvent*> (__first=0x555555dbf880, __last=0x555555dbf860, __result=0x555555dbf878) at /usr/lib64/gcc/x86_64-suse-linux/7/../../../../include/c++/7/bits/stl_algobase.h:368
#2  0x00007ffff7a31c89 in std::__copy_move_a<true, CHIPEvent**, CHIPEvent**> (__first=0x555555dbf880, __last=0x555555dbf860, __result=0x555555dbf878) at /usr/lib64/gcc/x86_64-suse-linux/7/../../../../include/c++/7/bits/stl_algobase.h:385
#3  0x00007ffff7b03bbf in std::__copy_move_a2<true, __gnu_cxx::__normal_iterator<CHIPEvent**, std::vector<CHIPEvent*, std::allocator<CHIPEvent*> > >, __gnu_cxx::__normal_iterator<CHIPEvent**, std::vector<CHIPEvent*, std::allocator<CHIPEvent*> > > > (__first=..., __last=..., __result=...) at /usr/lib64/gcc/x86_64-suse-linux/7/../../../../include/c++/7/bits/stl_algobase.h:422
#4  0x00007ffff7b03b47 in std::move<__gnu_cxx::__normal_iterator<CHIPEvent**, std::vector<CHIPEvent*, std::allocator<CHIPEvent*> > >, __gnu_cxx::__normal_iterator<CHIPEvent**, std::vector<CHIPEvent*, std::allocator<CHIPEvent*> > > > (__first=..., __last=..., __result=...) at /usr/lib64/gcc/x86_64-suse-linux/7/../../../../include/c++/7/bits/stl_algobase.h:487
#5  0x00007ffff7b03a09 in std::vector<CHIPEvent*, std::allocator<CHIPEvent*> >::_M_erase (this=0x55555593df68, __position=...) at /usr/lib64/gcc/x86_64-suse-linux/7/../../../../include/c++/7/bits/vector.tcc:157
#6  0x00007ffff7afe598 in std::vector<CHIPEvent*, std::allocator<CHIPEvent*> >::erase (this=0x55555593df68, __position=...) at /usr/lib64/gcc/x86_64-suse-linux/7/../../../../include/c++/7/bits/stl_vector.h:1180
#7  0x00007ffff7ae6e44 in CHIPStaleEventMonitorLevel0::monitor (this=0x555555d5f030) at /home/pvelesko/space/CHIP-SPV/src/backend/Level0/CHIPBackendLevel0.cc:631
#8  0x00007ffff7ac885e in CHIPEventMonitor::monitorWrapper (Arg=0x555555d5f030) at /home/pvelesko/space/CHIP-SPV/src/CHIPBackend.hh:321
#9  0x00007ffff68026ea in start_thread () from /lib64/libpthread.so.0
#10 0x00007ffff651aa8f in clone () from /lib64/libc.so.6
```

**Comment by pvelesko** [comment]
```
CHIP error [TID 443] [1667900780.254626317] : hipErrorTbd (StaleEventMonitor is trying to destroy an event which is already removed from backend event list) in /home/pvelesko/space/CHIP-SPV/src/backend/Level0/CHIPBackendLevel0.cc:630:monitor
```

**Comment by pjaaskel** [comment]
I cannot find this test. Is it still failing for you?

**Comment by pvelesko** [comment]
This is part of hip-tests. Will investigate later

**Comment by pvelesko** [comment]
Will need to revisit all failing tests post rebase merge
