### ISSUE TITLE
Catch2 + PoCL + LLVM16 Segfault

### ISSUE THREAD

**Issue by pvelesko** [CHIP-SPV/chipStar#558]
Running into this error:

```
===============================================================================
All tests passed (3 assertions in 1 test case)


Thread 1 "hipMallocPitch" received signal SIGSEGV, Segmentation fault.
0x00007ffff7c92ad5 in std::locale::~locale() () from /lib/x86_64-linux-gnu/libstdc++.so.6
(gdb)
(gdb) bt
#0  0x00007ffff7c92ad5 in std::locale::~locale() () from /lib/x86_64-linux-gnu/libstdc++.so.6
#1  0x00005555555f59b8 in std::basic_streambuf<char, std::char_traits<char> >::~basic_streambuf (this=<optimized out>) at /usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/streambuf:203
#2  std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::~basic_stringbuf (this=0x5555556e0d48) at /usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/sstream.tcc:291
#3  std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >::~basic_ostringstream (this=0x5555556e0d40, vtt=<optimized out>) at /usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/sstream:837
#4  std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >::~basic_ostringstream (this=0x5555556e0d40) at /usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/sstream:837
#5  Catch::TablePrinter::~TablePrinter (this=0x5555556e0d20) at /home/pvelesko/CHIP-SPV/CmdList/HIP/tests/catch/external/Catch2/catch.hpp:16301
#6  std::default_delete<Catch::TablePrinter>::operator() (this=this@entry=0x555555650808, __ptr=0x5555556e0d20) at /usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/unique_ptr.h:95
#7  0x00005555555b28ca in std::unique_ptr<Catch::TablePrinter, std::default_delete<Catch::TablePrinter> >::~unique_ptr (this=0x5555556e0d80) at /usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/unique_ptr.h:396
#8  Catch::ConsoleReporter::~ConsoleReporter (this=0x5555556506a0) at /home/pvelesko/CHIP-SPV/CmdList/HIP/tests/catch/external/Catch2/catch.hpp:16401
#9  0x00005555555b28e9 in Catch::ConsoleReporter::~ConsoleReporter (this=0x5555556e0d80) at /home/pvelesko/CHIP-SPV/CmdList/HIP/tests/catch/external/Catch2/catch.hpp:16401
#10 0x000055555559fe7b in std::default_delete<Catch::IStreamingReporter>::operator() (this=<optimized out>, __ptr=0x5555556e0d80) at /usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/unique_ptr.h:95
#11 std::unique_ptr<Catch::IStreamingReporter, std::default_delete<Catch::IStreamingReporter> >::~unique_ptr (this=0x7fffffff6a98) at /usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/unique_ptr.h:396
#12 Catch::RunContext::~RunContext (this=0x7fffffff6970) at /home/pvelesko/CHIP-SPV/CmdList/HIP/tests/catch/external/Catch2/catch.hpp:12665
#13 0x00005555555a6144 in Catch::(anonymous namespace)::TestGroup::~TestGroup (this=0x7fffffff6960) at /home/pvelesko/CHIP-SPV/CmdList/HIP/tests/catch/external/Catch2/catch.hpp:13261
#14 0x00005555555a5b89 in Catch::Session::runInternal (this=this@entry=0x7fffffff6c00) at /home/pvelesko/CHIP-SPV/CmdList/HIP/tests/catch/external/Catch2/catch.hpp:13502
#15 0x00005555555a4634 in Catch::Session::run (this=this@entry=0x7fffffff6c00) at /home/pvelesko/CHIP-SPV/CmdList/HIP/tests/catch/external/Catch2/catch.hpp:13449
#16 0x00005555555bb852 in Catch::Session::run<char> (this=0x7fffffff6c00, argc=<optimized out>, argv=<optimized out>) at /home/pvelesko/CHIP-SPV/CmdList/HIP/tests/catch/external/Catch2/catch.hpp:13171
#17 main (argc=2, argv=0x7fffffff6eb8) at /home/pvelesko/CHIP-SPV/CmdList/HIP/tests/catch/external/Catch2/catch.hpp:17448
```

**Comment by pvelesko** [comment]
```
Filters: Unit_hipMallocPitch_KernelLaunch - int
==1159392== Invalid read of size 8
==1159392==    at 0x555D24D: UnknownInlinedFun (Use.h:82)
==1159392==    by 0x555D24D: UnknownInlinedFun (Value.h:146)
==1159392==    by 0x555D24D: UnknownInlinedFun (Value.h:190)
==1159392==    by 0x555D24D: UnknownInlinedFun (linker.cpp:405)
==1159392==    by 0x555D24D: generateProgramBC(PoclLLVMContextData*, llvm::Module*, _cl_program*, _cl_device_id*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (pocl_llvm_build.cc:191)
==1159392==    by 0x5562F0E: pocl_llvm_link_program (pocl_llvm_build.cc:888)
==1159392==    by 0x5522880: pocl_llvm_convert_and_link_ir (common_driver.c:689)
==1159392==    by 0x552463C: pocl_driver_build_binary (common_driver.c:743)
==1159392==    by 0x54DCF4A: compile_and_link_program (pocl_build.c:862)
==1159392==    by 0x54DBABF: POclBuildProgram (clBuildProgram.c:37)
==1159392==    by 0x4F8B01E: clBuildProgram (ocl_icd_loader_gen.c:2072)
==1159392==    by 0x498C9BF: cl::Program::build(char const*, void (*)(_cl_program*, void*), void*) const (include/CL/opencl.hpp:6709)
==1159392==    by 0x497B071: CHIPModuleOpenCL::compile(chipstar::Device*) (src/backend/OpenCL/CHIPBackendOpenCL.cc:719)
==1159392==    by 0x498E41E: CHIPDeviceOpenCL::compile(SPVModule const&) (src/backend/OpenCL/CHIPBackendOpenCL.hh:201)
==1159392==    by 0x48FBED5: chipstar::Device::getOrCreateModule(SPVModule const&) (src/CHIPBackend.cc:990)
==1159392==    by 0x48FAF5C: chipstar::Device::prepareDeviceVariables(HostPtr) (src/CHIPBackend.cc:924)
==1159392==  Address 0x2415ae18 is 40 bytes inside a block of size 144 free'd
==1159392==    at 0x484B8AF: operator delete(void*) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==1159392==    by 0x939908F: llvm::Instruction::eraseFromParent() (in /home/pvelesko/install/clang/16.0/lib/libLLVMCore.so.16)
==1159392==    by 0x555D24C: UnknownInlinedFun (linker.cpp:426)
==1159392==    by 0x555D24C: generateProgramBC(PoclLLVMContextData*, llvm::Module*, _cl_program*, _cl_device_id*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (pocl_llvm_build.cc:191)
==1159392==    by 0x5562F0E: pocl_llvm_link_program (pocl_llvm_build.cc:888)
==1159392==    by 0x5522880: pocl_llvm_convert_and_link_ir (common_driver.c:689)
==1159392==    by 0x552463C: pocl_driver_build_binary (common_driver.c:743)
==1159392==    by 0x54DCF4A: compile_and_link_program (pocl_build.c:862)
==1159392==    by 0x54DBABF: POclBuildProgram (clBuildProgram.c:37)
==1159392==    by 0x4F8B01E: clBuildProgram (ocl_icd_loader_gen.c:2072)
==1159392==    by 0x498C9BF: cl::Program::build(char const*, void (*)(_cl_program*, void*), void*) const (include/CL/opencl.hpp:6709)
==1159392==    by 0x497B071: CHIPModuleOpenCL::compile(chipstar::Device*) (src/backend/OpenCL/CHIPBackendOpenCL.cc:719)
==1159392==    by 0x498E41E: CHIPDeviceOpenCL::compile(SPVModule const&) (src/backend/OpenCL/CHIPBackendOpenCL.hh:201)
==1159392==  Block was alloc'd at
==1159392==    at 0x4849013: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==1159392==    by 0x944D228: llvm::User::operator new(unsigned long, unsigned int, unsigned int) (in /home/pvelesko/install/clang/16.0/lib/libLLVMCore.so.16)
==1159392==    by 0x9152AD2: (anonymous namespace)::BitcodeReader::parseFunctionBody(llvm::Function*) (in /home/pvelesko/install/clang/16.0/lib/libLLVMBitReader.so.16)
==1159392==    by 0x9156E29: (anonymous namespace)::BitcodeReader::materialize(llvm::GlobalValue*) (in /home/pvelesko/install/clang/16.0/lib/libLLVMBitReader.so.16)
==1159392==    by 0x9157755: (anonymous namespace)::BitcodeReader::materializeModule() (in /home/pvelesko/install/clang/16.0/lib/libLLVMBitReader.so.16)
==1159392==    by 0x93FA6AD: llvm::Module::materializeAll() (in /home/pvelesko/install/clang/16.0/lib/libLLVMCore.so.16)
==1159392==    by 0x9159422: llvm::BitcodeModule::getModuleImpl(llvm::LLVMContext&, bool, bool, bool, llvm::ParserCallbacks) (in /home/pvelesko/install/clang/16.0/lib/libLLVMBitReader.so.16)
==1159392==    by 0x915A07F: llvm::parseBitcodeFile(llvm::MemoryBufferRef, llvm::LLVMContext&, llvm::ParserCallbacks) (in /home/pvelesko/install/clang/16.0/lib/libLLVMBitReader.so.16)
==1159392==    by 0x557433C: parseModuleIRMem(char const*, unsigned long, llvm::LLVMContext*) (pocl_llvm_utils.cc:116)
==1159392==    by 0x55629B7: pocl_llvm_link_program (pocl_llvm_build.cc:855)
==1159392==    by 0x5522880: pocl_llvm_convert_and_link_ir (common_driver.c:689)
==1159392==    by 0x552463C: pocl_driver_build_binary (common_driver.c:743)
==1159392==
==1159392== Thread 7:
==1159392== Invalid read of size 4
==1159392==    at 0x22168030: _pocl_kernel__Z8copy_varIiEvPT_S1_mm (in /home/pvelesko/.cache/pocl/kcache/KD/LLNMMNEMJLLEDDOBNMFEJPBLNFPBLMIFAHMAG/_Z8copy_varIiEvPT_S1_mm/1-1-1-goffs0-smallgrid/_Z8copy_varIiEvPT_S1_mm.so)
==1159392==    by 0x4DE4B42: start_thread (pthread_create.c:442)
==1159392==    by 0x4E75BB3: clone (clone.S:100)
==1159392==  Address 0xc8e2300 is 16 bytes after a block of size 64 in arena "client"
==1159392==
==1159392== Invalid write of size 4
==1159392==    at 0x22168034: _pocl_kernel__Z8copy_varIiEvPT_S1_mm (in /home/pvelesko/.cache/pocl/kcache/KD/LLNMMNEMJLLEDDOBNMFEJPBLNFPBLMIFAHMAG/_Z8copy_varIiEvPT_S1_mm/1-1-1-goffs0-smallgrid/_Z8copy_varIiEvPT_S1_mm.so)
==1159392==    by 0x4DE4B42: start_thread (pthread_create.c:442)
==1159392==    by 0x4E75BB3: clone (clone.S:100)
==1159392==  Address 0x5466e00 is 8 bytes after a block of size 56 alloc'd
==1159392==    at 0x4849013: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==1159392==    by 0x49959F1: allocate (new_allocator.h:137)
==1159392==    by 0x49959F1: allocate (alloc_traits.h:464)
==1159392==    by 0x49959F1: _M_get_node (stl_tree.h:561)
==1159392==    by 0x49959F1: _M_create_node<std::shared_ptr<void> &, unsigned long &> (stl_tree.h:611)
==1159392==    by 0x49959F1: _Auto_node<std::shared_ptr<void> &, unsigned long &> (stl_tree.h:1636)
==1159392==    by 0x49959F1: _M_emplace_hint_unique<std::shared_ptr<void> &, unsigned long &> (stl_tree.h:2461)
==1159392==    by 0x49959F1: emplace_hint<std::shared_ptr<void> &, unsigned long &> (stl_map.h:638)
==1159392==    by 0x49959F1: emplace<std::shared_ptr<void> &, unsigned long &> (stl_map.h:599)
==1159392==    by 0x49959F1: SVMemoryRegion::allocate(unsigned long, SVMemoryRegion::SVM_ALLOC_GRANULARITY) (src/backend/OpenCL/SVMemoryRegion.cc:49)
==1159392==    by 0x497DDDB: CHIPContextOpenCL::allocateImpl(unsigned long, unsigned long, hipMemoryType, chipstar::HostAllocFlags) (src/backend/OpenCL/CHIPBackendOpenCL.cc:878)
==1159392==    by 0x48FD6AF: chipstar::Context::allocate(unsigned long, unsigned long, hipMemoryType, chipstar::HostAllocFlags) (src/CHIPBackend.cc:1147)
==1159392==    by 0x4945324: hipMallocPitch3DInternal (src/CHIPBindings.cc:2706)
==1159392==    by 0x4945324: hipMallocPitch (src/CHIPBindings.cc:2720)
==1159392==    by 0x132B8E: void ____C_A_T_C_H____T_E_M_P_L_A_T_E____T_E_S_T____F_U_N_C____103<int>() (HIP/tests/catch/unit/memory/hipMallocPitch.cc:526)
==1159392==    by 0x157F88: invoke (HIP/tests/catch/external/Catch2/catch.hpp:14100)
==1159392==    by 0x157F88: invokeActiveTestCase (HIP/tests/catch/external/Catch2/catch.hpp:12959)
==1159392==    by 0x157F88: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (HIP/tests/catch/external/Catch2/catch.hpp:12932)
==1159392==    by 0x15757E: Catch::RunContext::runTest(Catch::TestCase const&) (HIP/tests/catch/external/Catch2/catch.hpp:12693)
==1159392==    by 0x15CEB1: execute (HIP/tests/catch/external/Catch2/catch.hpp:13287)
==1159392==    by 0x15CEB1: Catch::Session::runInternal() (HIP/tests/catch/external/Catch2/catch.hpp:13493)
==1159392==    by 0x15B9B4: Catch::Session::run() (HIP/tests/catch/external/Catch2/catch.hpp:13449)
==1159392==    by 0x172C21: run<char> (HIP/tests/catch/external/Catch2/catch.hpp:13171)
==1159392==    by 0x172C21: main (HIP/tests/catch/external/Catch2/catch.hpp:17448)
==1159392==
==1159392== Invalid read of size 4
==1159392==    at 0x2216803E: _pocl_kernel__Z8copy_varIiEvPT_S1_mm (in /home/pvelesko/.cache/pocl/kcache/KD/LLNMMNEMJLLEDDOBNMFEJPBLNFPBLMIFAHMAG/_Z8copy_varIiEvPT_S1_mm/1-1-1-goffs0-smallgrid/_Z8copy_varIiEvPT_S1_mm.so)
==1159392==    by 0x4DE4B42: start_thread (pthread_create.c:442)
==1159392==    by 0x4E75BB3: clone (clone.S:100)
==1159392==  Address 0xc8e2500 is 32 bytes before a block of size 64 in arena "client"
==1159392==
===============================================================================
All tests passed (3 assertions in 1 test case)

==1159392==
==1159392== HEAP SUMMARY:
==1159392==     in use at exit: 362,442,220 bytes in 744,479 blocks
==1159392==   total heap usage: 922,340 allocs, 177,861 frees, 459,002,955 bytes allocated
==1159392==
==1159392== LEAK SUMMARY:
==1159392==    definitely lost: 1,048 bytes in 7 blocks
==1159392==    indirectly lost: 905,475 bytes in 2,678 blocks
==1159392==      possibly lost: 66,497,126 bytes in 543,664 blocks
==1159392==    still reachable: 295,038,571 bytes in 198,130 blocks
==1159392==                       of which reachable via heuristic:
==1159392==                         multipleinheritance: 218,856 bytes in 1 blocks
==1159392==         suppressed: 0 bytes in 0 blocks
==1159392== Rerun with --leak-check=full to see details of leaked memory
==1159392==
==1159392== For lists of detected and suppressed errors, rerun with: -s
==1159392== ERROR SUMMARY: 10 errors from 4 contexts (suppressed: 0 from 0)
╭─pvelesko@cupcake ~/CHIP-SPV/CmdList/build ‹rc1Fixes●›
╰─$
╭─pvelesko@cupcake ~/CHIP-SPV/CmdList/build ‹rc1Fixes●›
╰─$
```

**Comment by pvelesko** [comment]
This is happening only on CI using clang 16. Tested with old PoCL and new 4.0 release. 
Removing the kernel execution makes this error go away. 
On Sunspot this error does not occur llvm16+pocl4.0

**Comment by pvelesko** [comment]
Stack corruption unrelated to catch2 or llvm
