### ISSUE TITLE
libCEED application hang on exceeding some problem size threshold

### ISSUE THREAD

**Issue by pvelesko** [CHIP-SPV/chipStar#565]
The same problem runs successfully on OpenCL CPU but fails on dGPU for both OpenCL and Level Zero

Failure happens during finish() for first-touch memcopy which is done inside of a hipMalloc. 

Perhaps we're not checking if malloc passed? 
```
Thread 1 "bp3-mult" received signal SIGINT, Interrupt.
0x000015552a89fd2d in ?? () from /soft/libraries/intel-gpu-umd/20230622.1-agama-devel-647.9/driver/lib64/intel-opencl/libigdrcl.so
(gdb) bt
#0  0x000015552a89fd2d in ?? () from /soft/libraries/intel-gpu-umd/20230622.1-agama-devel-647.9/driver/lib64/intel-opencl/libigdrcl.so
#1  0x000015552a68988c in ?? () from /soft/libraries/intel-gpu-umd/20230622.1-agama-devel-647.9/driver/lib64/intel-opencl/libigdrcl.so
#2  0x000015552a825236 in ?? () from /soft/libraries/intel-gpu-umd/20230622.1-agama-devel-647.9/driver/lib64/intel-opencl/libigdrcl.so
#3  0x000015552a622300 in ?? () from /soft/libraries/intel-gpu-umd/20230622.1-agama-devel-647.9/driver/lib64/intel-opencl/libigdrcl.so
#4  0x000015552a823b7a in ?? () from /soft/libraries/intel-gpu-umd/20230622.1-agama-devel-647.9/driver/lib64/intel-opencl/libigdrcl.so
#5  0x000015552a5c76fa in ?? () from /soft/libraries/intel-gpu-umd/20230622.1-agama-devel-647.9/driver/lib64/intel-opencl/libigdrcl.so
#6  0x0000155554e49788 in cl::CommandQueue::finish (this=0x555557eed640) at /home/pvelesko/chipStar_1.0/include/CL/opencl.hpp:8806
#7  0x0000155554e3ecf4 in CHIPQueueOpenCL::finish (this=0x55555747bf10) at /home/pvelesko/chipStar_1.0/src/backend/OpenCL/CHIPBackendOpenCL.cc:1181
#8  0x0000155554d7ae32 in chipstar::Queue::memCopy (this=0x55555747bf10, Dst=0xff90544a600000, Src=0x7fffffff6a3f, Size=1) at /home/pvelesko/chipStar_1.0/src/CHIPBackend.cc:1558
#9  0x0000155554de4ea0 in hipMallocInternal (Ptr=0x555558049778, Size=114726920) at /home/pvelesko/chipStar_1.0/src/CHIPBindings.cc:2415
#10 0x0000155554de4bfa in hipMalloc (Ptr=0x555558049778, Size=114726920) at /home/pvelesko/chipStar_1.0/src/CHIPBindings.cc:2426
#11 0x0000155555165c1b in CeedVectorSyncH2D_Hip (vec=0x555558049680) at /home/pvelesko/libCEED/backends/hip-ref/ceed-hip-ref-vector.c:59
#12 0x0000155555163615 in CeedVectorSyncArray_Hip (vec=0x555558049680, mem_type=CEED_MEM_DEVICE) at /home/pvelesko/libCEED/backends/hip-ref/ceed-hip-ref-vector.c:111
#13 0x000015555510011c in CeedVectorSyncArray (vec=0x555558049680, mem_type=CEED_MEM_DEVICE) at /home/pvelesko/libCEED/interface/ceed-vector.c:311
#14 0x0000155555164a76 in CeedVectorPointwiseMult_Hip (w=0x555559aaf4e0, x=0x555558049680, y=0x555559aaf4e0) at /home/pvelesko/libCEED/backends/hip-ref/ceed-hip-ref-vector.c:660
#15 0x0000155555101b9f in CeedVectorPointwiseMult (w=0x555559aaf4e0, x=0x555558049680, y=0x555559aaf4e0) at /home/pvelesko/libCEED/interface/ceed-vector.c:715
#16 0x0000555555556d93 in main ()
```

**Comment by pvelesko** [comment]
Ran on cupcake, after a while it runs out of GPU memory. Needs the switch to imm command lists.
