### ISSUE TITLE
Unit_hipGraphDestroyNode_DestroyDependencyNode segfault (iGPU, OpenCL)

### ISSUE THREAD

**Issue by pjaaskel** [CHIP-SPV/chipStar#654]
```
Thread 1 "hipGraphDestroy" received signal SIGSEGV, Segmentation fault.
0x0000555557227010 in ?? ()
(gdb) bt
#0  0x0000555557227010 in ?? ()
#1  0x00007ffff7d3e195 in CHIPGraph::CHIPGraph (this=0x5555572a37b8, OriginalGraph=...) at /home/pjaaskel/src/chipStar/src/CHIPGraph.cc:72
#2  0x00007ffff7d9bf80 in CHIPGraphExec::CHIPGraphExec (this=0x5555572a37b0, Graph=0x5555564de460)
    at /home/pjaaskel/src/chipStar/src/CHIPGraph.hh:682
#3  0x00007ffff7d6060f in hipGraphInstantiate (pGraphExec=0x7fffffffce90, graph=0x5555564de460, pErrorNode=0x0, pLogBuffer=0x0, 
    bufferSize=0) at /home/pjaaskel/src/chipStar/src/CHIPBindings.cc:481
#4  0x00005555555a03a3 in ____C_A_T_C_H____T_E_S_T____43 ()
    at /home/pjaaskel/src/chipStar/HIP/tests/catch/unit/graph/hipGraphDestroyNode.cc:128
#5  0x00005555555c0573 in Catch::TestInvokerAsFunction::invoke (this=0x55555570d9c0)
    at /home/pjaaskel/src/chipStar/HIP/tests/catch/external/Catch2/catch.hpp:14261
#6  0x00005555555bab84 in Catch::TestCase::invoke (this=0x5555564de9a0)
    at /home/pjaaskel/src/chipStar/HIP/tests/catch/external/Catch2/catch.hpp:14100
#7  0x00005555555baaba in Catch::RunContext::invokeActiveTestCase (this=0x7fffffffd6d0)
    at /home/pjaaskel/src/chipStar/HIP/tests/catch/external/Catch2/catch.hpp:12959
#8  0x00005555555b975e in Catch::RunContext::runCurrentTest (this=0x7fffffffd6d0, Python Exception <class 'gdb.error'>: There is no member named _M_p.
redirectedCout=, Python Exception <class 'gdb.error'>: There is no member named _M_p.
redirectedCerr=)
    at /home/pjaaskel/src/chipStar/HIP/tests/catch/external/Catch2/catch.hpp:12932
#9  0x00005555555b8be5 in Catch::RunContext::runTest (this=0x7fffffffd6d0, testCase=...)
    at /home/pjaaskel/src/chipStar/HIP/tests/catch/external/Catch2/catch.hpp:12693
#10 0x00005555555bd283 in Catch::(anonymous namespace)::TestGroup::execute (this=0x7fffffffd6c0)
    at /home/pjaaskel/src/chipStar/HIP/tests/catch/external/Catch2/catch.hpp:13287
#11 0x00005555555bc8ab in Catch::Session::runInternal (this=0x7fffffffd9e0)
    at /home/pjaaskel/src/chipStar/HIP/tests/catch/external/Catch2/catch.hpp:13493
#12 0x00005555555bc697 in Catch::Session::run (this=0x7fffffffd9e0)
    at /home/pjaaskel/src/chipStar/HIP/tests/catch/external/Catch2/catch.hpp:13449
#13 0x00005555555ed23a in Catch::Session::run<char> (this=0x7fffffffd9e0, argc=2, argv=0x7fffffffdc98)
    at /home/pjaaskel/src/chipStar/HIP/tests/catch/external/Catch2/catch.hpp:13171
#14 0x00005555555d23ef in main (argc=2, argv=0x7fffffffdc98) at /home/pjaaskel/src/chipStar/HIP/tests/catch/external/Catch2/catch.hpp:17448
```

**Comment by pvelesko** [comment]
Known to fail on all platforms - seems like bitrot and will not be relevant once Michal's graphs PRs are merged.
